name: authentication
description: A new Flutter package project.
version: 0.0.1
homepage: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pinput: ^2.2.12
  equatable: ^2.0.5
  flutter_svg: ^0.22.0
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  flutter_bloc: ^8.1.1
  google_sign_in: ^5.4.1
  config:
    git: https://github.com/rahulsharmadev-community/config.git

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flags/
